version: "3.7"
services:
  jenkins:
    image: private/jenkins:latest
    restart: always
    ports:
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/jenkins_home:/var/jenkins_home